/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoagencia;

import Controller.ClienteController;
import beans.Cliente;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;



/**
 *
 * @author ASUS
 */
public class frmCliente extends javax.swing.JFrame {
private ClienteController clienteController = new ClienteController();
public static DefaultTableModel dtmCliente = new DefaultTableModel();
private SimpleDateFormat dia=new SimpleDateFormat("dd/MM/yyyy");
  
    public frmCliente() {
        initComponents();
        llenaTabla();
        listar();
    }
     public void llenaTabla(){
        dtmCliente.addColumn("CODIGO");
        dtmCliente.addColumn("NOMBRES");
        dtmCliente.addColumn("APE PATERNO");
        dtmCliente.addColumn("APE MATERNO");
        dtmCliente.addColumn("FECHA DE NACIMIENTO");
        dtmCliente.addColumn("ESTADO");
        dtmCliente.addColumn("DNI");
        dtmCliente.addColumn("CORREO");
        dtmCliente.addColumn("SEXO");
        //
        this.tbCliente.setModel(dtmCliente);
    }
    public void listar(){
        dtmCliente.setNumRows(0);
        for(int i=0;i<clienteController.size();i++){
            Object[] vector=new Object[9];
            vector[0] = clienteController.get(i).getCodigo();
            vector[1] = clienteController.get(i).getNombre();
            vector[2] = clienteController.get(i).getApellidoPaterno();
            vector[3] = clienteController.get(i).getApellidoMaterno();
            vector[4] = clienteController.get(i).getFechaN();
            vector[5] = clienteController.get(i).getEstado();
            vector[6] = clienteController.get(i).getDni();
            vector[7] = clienteController.get(i).getCorreo();
            vector[8] = clienteController.get(i).getSexo();
            dtmCliente.addRow(vector);
        }
        tbCliente.setModel(dtmCliente);
    }


public void limpiar(){
         txtNombres.setText("");
         txtApePaterno.setText("");
         txtApeMaterno.setText("");
         txtDni.setText("");
         txtCorreo.setText("");
         cboSexo.setSelectedIndex(0);
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        dateUtil1 = new com.toedter.calendar.DateUtil();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApeMaterno = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApePaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        btnRegistar = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jdFecha = new com.toedter.calendar.JDateChooser();
        txtBuscar = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellido Materno");

        jLabel3.setText("DNI");

        jLabel4.setText("Código");

        txtApeMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeMaternoActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido Paterno");

        jLabel7.setText("Correo electrónico");

        jLabel8.setText("Sexo");

        jLabel9.setText("Fecha de Nacimiento");

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger", "Masculino", "Femenino" }));

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCliente);

        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnFactura.setText("Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("REGISTRO DE CLIENTES");

        jLabel5.setText("Buscar por DNI");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jdFecha.setDateFormatString("dd/MM/yyyy");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel11.setText("Estado");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApePaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(192, 192, 192)
                                    .addComponent(jLabel11)
                                    .addGap(43, 43, 43)
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(btnNuevo)
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFactura)
                            .addGap(70, 70, 70)
                            .addComponent(btnEditar))))
                .addGap(41, 130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistar)
                    .addComponent(btnFactura)
                    .addComponent(btnEditar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApeMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeMaternoActionPerformed

    }//GEN-LAST:event_txtApeMaternoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       txtCodigo.setText(""+clienteController.obtenerCorrelativo());
          limpiar();
          txtCodigo.requestFocus();
         
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
    int msg = JOptionPane.showConfirmDialog(this, "Deseas Grabar el Registro","Grabar",JOptionPane.YES_NO_OPTION);
    if(msg == JOptionPane.YES_OPTION){
              
        Cliente cliente = new Cliente();
        cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
        cliente.setNombre(txtNombres.getText());
        cliente.setApellidoPaterno(txtApePaterno.getText());
        cliente.setApellidoMaterno(txtApeMaterno.getText());
        cliente.setFechaN(dia.format(jdFecha.getDate()));
        cliente.setEstado(cboEstado.getSelectedItem().toString());
        cliente.setDni(txtDni.getText());
        cliente.setCorreo(txtCorreo.getText());
        cliente.setSexo(cboSexo.getSelectedItem().toString());
        
        
        
        clienteController.agregar(cliente);

        clienteController.grabar();
        listar();
        JOptionPane.showMessageDialog(this,"Registro grabado satisfactoriamente!!!");
        
    }else{
         txtNombres.requestFocus();
    }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked
    txtCodigo.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(),0).toString());
    txtNombres.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 1).toString());
    txtApePaterno.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 2).toString());
    txtApeMaterno.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 3).toString());
    jdFecha.setDateFormatString(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 4).toString());
    cboEstado.setSelectedItem(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 5).toString());
    txtDni.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 6).toString());
    txtCorreo.setText(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 7).toString());
    cboSexo.setSelectedItem(dtmCliente.getValueAt(tbCliente.getSelectedRow(), 8).toString());
    
    
    
    
   
 
    }//GEN-LAST:event_tbClienteMouseClicked

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
    this.setVisible(false);
    frmFactura me= new frmFactura();
    me.setVisible(true);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
    
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
    dtmCliente.setNumRows(0);
        for(int i=0;i<clienteController.size();i++){
           if(clienteController.get(i).getDni().contains(txtBuscar.getText())){
            Object[] vector=new Object[9];
            vector[0] = clienteController.get(i).getCodigo();
            vector[1] = clienteController.get(i).getNombre();
            vector[2] = clienteController.get(i).getApellidoPaterno();
            vector[3] = clienteController.get(i).getApellidoMaterno();
            vector[4] = clienteController.get(i).getFechaN();
            vector[5] = clienteController.get(i).getEstado();
            vector[6] = clienteController.get(i).getDni();
            vector[7] = clienteController.get(i).getCorreo();
            vector[8] = clienteController.get(i).getSexo();
            dtmCliente.addRow(vector);
            }
        }
        tbCliente.setModel(dtmCliente);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int msg = JOptionPane.showConfirmDialog(this, "Deseas Modificar el Registro","Modificar",JOptionPane.YES_NO_OPTION);
        if(msg == JOptionPane.YES_OPTION){
            Cliente cliente = clienteController.buscar(Integer.parseInt(txtCodigo.getText()));
            if(cliente != null){
                cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
                cliente.setNombre(txtNombres.getText());
                cliente.setApellidoPaterno(txtApePaterno.getText());
                cliente.setApellidoMaterno(txtApeMaterno.getText());
                cliente.setFechaN(dia.format(jdFecha.getDateFormatString()));
                cliente.setDni(txtDni.getText());
                cliente.setCorreo(txtCorreo.getText());
                cliente.setEstado(cboEstado.getSelectedItem().toString());
                cliente.setSexo(cboSexo.getSelectedItem().toString());
                listar();
                
                clienteController.grabar();
                
                JOptionPane.showMessageDialog(this,"Registro Actualizado satisfactoriamente!!!");
                
            }else{
                JOptionPane.showMessageDialog(this,"Objeto no encontrado!!!");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboSexo;
    private com.toedter.calendar.DateUtil dateUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser jdFecha;
    private java.awt.Label label1;
    public static javax.swing.JTable tbCliente;
    private javax.swing.JTextField txtApeMaterno;
    private javax.swing.JTextField txtApePaterno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
