/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoagencia;

import Controller.ClienteController;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Controller.FacturaController;
import Controller.PaisController;
import beans.Factura;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */


public class frmFactura extends javax.swing.JFrame implements Runnable {
private ClienteController ClienteController = new ClienteController();
private FacturaController FacturaController = new FacturaController();
private PaisController PaisController = new PaisController();
public static DefaultTableModel dtmCliente = new DefaultTableModel();
private DefaultTableModel dtmFactura = new DefaultTableModel();
private SimpleDateFormat dia=new SimpleDateFormat("dd/MM/yyyy");



String hora, minutos,segundos;
Thread hilo;
  
    /**
     * Creates new form frmFactura
     */
    public frmFactura() {
        initComponents();
        llenaTabla();
        hilo= new Thread(this);
        hilo.start();
        setVisible(true);
        txtCantidad.setText(""+FacturaController.size());

        for(int i=0;i<PaisController.size();i++){
            cboDestino.addItem(PaisController.get(i).getNombrePais());
        }
    }
    public void llenaTabla(){
        dtmCliente.addColumn("NOMBRES");
        dtmCliente.addColumn("APE PATERNO");
        dtmCliente.addColumn("APE MATERNO");
        dtmCliente.addColumn("ESTADO");
        dtmCliente.addColumn("DNI");
        dtmCliente.addColumn("SEXO");
        
        this.tbCliente2.setModel(dtmCliente);
        dtmFactura.addColumn("N°VUELO");  
        dtmFactura.addColumn("NOMBRES");
        dtmFactura.addColumn("A.PATERNO");
        dtmFactura.addColumn("A.MATERNO");
        dtmFactura.addColumn("DNI");
        dtmFactura.addColumn("SEXO");
        dtmFactura.addColumn("PARTIDA");
        dtmFactura.addColumn("DESTINO");
        dtmFactura.addColumn("FECHA SALIDA");
        dtmFactura.addColumn("HORA REGISTRO");
        dtmFactura.addColumn("ASIENTO");
        dtmFactura.addColumn("CLASE");
        dtmFactura.addColumn("EQUIPAJE");
        dtmFactura.addColumn("PUERTA");
        dtmFactura.addColumn("TIPO PAGO");
        dtmFactura.addColumn("TICKET");
        dtmFactura.addColumn("TARIFA CLASE");
        dtmFactura.addColumn("PRECIO VIAJE");
        dtmFactura.addColumn("COSTO PASAJE(+IGV)");
        dtmFactura.addColumn("ESTADO");
        this.tbFactura.setModel(dtmFactura);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApeMaterno = new javax.swing.JTextField();
        txtApePaterno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtVuelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboClase = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPartida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cboDestino = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboEquipaje = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cboPuerta = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtTicket = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFactura = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPrecioViaje = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCostoPasaje = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtSalida = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        txtBuscaDNI = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FACTURA");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIDO PATERNO");

        jLabel4.setText("APELLIDO MATERNO");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(204, 204, 204));

        txtApeMaterno.setEditable(false);
        txtApeMaterno.setBackground(new java.awt.Color(204, 204, 204));

        txtApePaterno.setEditable(false);
        txtApePaterno.setBackground(new java.awt.Color(204, 204, 204));

        tbCliente2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCliente2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCliente2);

        jLabel5.setText("DNI");

        txtDni.setEditable(false);
        txtDni.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Sexo");

        txtSexo.setEditable(false);
        txtSexo.setBackground(new java.awt.Color(204, 204, 204));

        btnMostrar.setText("Mostrar Clientes");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel7.setText("NÚMERO DE VUELO");

        txtVuelo.setEditable(false);
        txtVuelo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Clase");

        cboClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Económica", "Ejecutiva", "Primera Clase" }));
        cboClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClaseActionPerformed(evt);
            }
        });

        jLabel9.setText("PARTIDA");

        txtPartida.setEditable(false);
        txtPartida.setBackground(new java.awt.Color(204, 204, 204));
        txtPartida.setText("LIMA");

        jLabel10.setText("FECHA DE SALIDA");

        jLabel11.setText("HORA DE REGISTRO");

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setText("ASIENTO");

        txtAsiento.setEditable(false);
        txtAsiento.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setText("Destino");

        cboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDestinoActionPerformed(evt);
            }
        });

        jLabel14.setText("EQUIPAJE");

        cboEquipaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger", "Sí", "No" }));

        jLabel15.setText("PUERTA DE EMBARQUE");

        cboPuerta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel16.setText("TIPO DE PAGO");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));

        jLabel17.setText("TICKET");

        txtTicket.setEditable(false);

        jLabel18.setText("TARIFA");

        txtTarifa.setEditable(false);

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel19.setText("BUSCAR POR DNI:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        tbFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbFactura);

        jLabel20.setText("TOTAL A PAGAR:");

        jLabel21.setText("CANTIDAD DE PERSONAS:");

        jLabel22.setText("PRECIO DE VIAJE");

        jLabel23.setText("COSTO DEL PASAJE");

        txtCostoPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoPasajeActionPerformed(evt);
            }
        });

        jLabel24.setText("Estado");

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setText("BUSCAR POR DNI");

        txtBuscaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaDNIActionPerformed(evt);
            }
        });
        txtBuscaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaDNIKeyReleased(evt);
            }
        });

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnNuevo)
                                .addGap(339, 339, 339)
                                .addComponent(btnGuardar)
                                .addGap(354, 354, 354)
                                .addComponent(btnEditar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(282, 282, 282)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel14))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                            .addComponent(txtDni)
                                                            .addComponent(txtVuelo)
                                                            .addComponent(cboEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(34, 34, 34))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(2, 2, 2)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel3)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel9)
                                                            .addComponent(jLabel11))
                                                        .addGap(26, 26, 26)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtApeMaterno)
                                                            .addComponent(txtApePaterno)
                                                            .addComponent(txtPartida)
                                                            .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cboPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(40, 40, 40)
                                                        .addComponent(jLabel16))))
                                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAsiento)
                                                    .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel17)
                                                .addGap(39, 39, 39)
                                                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(186, 186, 186)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cboClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEstado)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(btnMostrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel23)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtCostoPasaje)
                                                        .addGap(3, 3, 3))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel22)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(txtPrecioViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel18)))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(51, 51, 51)
                        .addComponent(txtBuscaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtBuscaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMostrar)
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(cboEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(cboPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtPrecioViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCostoPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnEditar))
                    .addComponent(btnNuevo))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir)
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
  tbCliente2.setModel (frmCliente.dtmCliente);    
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void tbCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCliente2MouseClicked
    txtNombre.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),1).toString());
    txtApePaterno.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),2).toString());
    txtApeMaterno.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),3).toString());
    txtDni.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),6).toString());
    txtSexo.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),8).toString());
    txtEstado.setText(frmCliente.dtmCliente.getValueAt(tbCliente2.getSelectedRow(),5).toString());
    }//GEN-LAST:event_tbCliente2MouseClicked
    public void listar(){
 dtmFactura.setNumRows(0);
for(int i=0;i<FacturaController.size();i++){
        Object[] vector = new Object[20];
        vector[0] = FacturaController.get(i).getNumeroVuelo();
        vector[1] = FacturaController.get(i).getNombre();
        vector[2] = FacturaController.get(i).getApellidoPaterno();
        vector[3] = FacturaController.get(i).getApellidoMaterno();
        vector[4] = FacturaController.get(i).getDni(); 
        vector[5] = FacturaController.get(i).getSexo(); 
        vector[6] = FacturaController.get(i).getPartida();
        vector[7] = FacturaController.get(i).getDestino();
        vector[8] = FacturaController.get(i).getSalida();
        vector[9] = FacturaController.get(i).getHora();
        vector[10] = FacturaController.get(i).getAsiento();
        vector[11] = FacturaController.get(i).getClase();
        vector[12] = FacturaController.get(i).getEquipaje(); 
        vector[13] = FacturaController.get(i).getPuertaEmbarque(); 
        vector[14] = FacturaController.get(i).getTipoPago(); 
        vector[15] = FacturaController.get(i).getTicket(); 
        vector[16] = FacturaController.get(i).getTarifa();
        vector[17] = FacturaController.get(i).getPrecioViaje();
        vector[18] = FacturaController.get(i).getCostoPasaje();
        vector[19] =FacturaController.get(i).getEstado();
        
        
        dtmFactura.addRow(vector);
 }
tbFactura.setModel(dtmFactura);
}
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    
    int msg = JOptionPane.showConfirmDialog(this, "Deseas Grabar el Registro","Grabar",JOptionPane.YES_NO_OPTION);
    if(msg == JOptionPane.YES_OPTION){
        Factura factura = new Factura();
        factura.setNumeroVuelo(txtVuelo.getText());
        factura.setTicket(txtTicket.getText());
        factura.setNombre(txtNombre.getText());
        factura.setApellidoPaterno(txtApePaterno.getText());
        factura.setApellidoMaterno(txtApeMaterno.getText());
        factura.setDni(txtDni.getText());
        factura.setSexo(txtSexo.getText());
        factura.setPartida(txtPartida.getText());
        factura.setDestino(cboDestino.getSelectedItem().toString());
        factura.setSalida(dia.format(txtSalida.getDate()));
        factura.setHora(txtHora.getText());
        factura.setAsiento(txtAsiento.getText());
        factura.setClase(cboClase.getSelectedItem().toString()); 
        factura.setEquipaje(cboEquipaje.getSelectedItem().toString());
        factura.setTipoPago(cboTipo.getSelectedItem().toString());
        factura.setNombrePais(cboDestino.getSelectedItem().toString()); 
        factura.setPuertaEmbarque(cboPuerta.getSelectedItem().toString());
        factura.setTarifa(Double.parseDouble(txtTarifa.getText()));
        factura.setPrecioViaje(Double.parseDouble(txtPrecioViaje.getText()));
        factura.setCostoPasaje(Double.parseDouble(txtCostoPasaje.getText()));
        factura.setEstado(txtEstado.getText());
        
        //Insertar el objeto al arreglo
        FacturaController.add(factura);
           txtCantidad.setText(""+FacturaController.size());
        
        listar();
        limpiar();
        
        
        
        JOptionPane.showMessageDialog(this,"Registro grabado satisfactoriamente!!!");
  
    }else{
         txtSalida.requestFocus();
    }
       txtCantidad.setText(""+FacturaController.size());
       txtTotal.setText(""+getTotal());

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    txtTicket.setText("T" + FacturaController.getNumeroVuelo());
    txtAsiento.setText(""+FacturaController.getAsiento()+FacturaController.getNumero());
  //Limpiar todo
    }//GEN-LAST:event_btnNuevoActionPerformed
    private double getTotal(){
        double acum=0;
        for(int i=0;i<FacturaController.listaFactura.size();i++){
            acum=acum+FacturaController.listaFactura.get(i).getCostoPasaje();
        }
          return acum;   
    }
    private void cboClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClaseActionPerformed
    switch(cboClase.getSelectedIndex()){
        case 0: txtTarifa.setText("");
            break;
        case 1: txtTarifa.setText("50.45");
            break;
        case 2: txtTarifa.setText("150.48");
            break;
        case 3: txtTarifa.setText("200.54");
            break;
    }
    DecimalFormat formato = new DecimalFormat("#,###.00");
    txtCostoPasaje.setText(""+formato.format(hallartotalpasaje()));
    
    }//GEN-LAST:event_cboClaseActionPerformed

    private void cboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDestinoActionPerformed
    switch(cboDestino.getSelectedIndex()){
        case 0: txtPrecioViaje.setText("250.28");
                txtVuelo.setText("V0001");
            break;
        case 1: txtPrecioViaje.setText("240.28");
                txtVuelo.setText("V0002");
            break;
        case 2: txtPrecioViaje.setText("150.18");
                txtVuelo.setText("V0003");
            break;
        case 3: txtPrecioViaje.setText("150.88");
                txtVuelo.setText("V0004");
                
            break;
        case 4: txtPrecioViaje.setText("180.14");
                txtVuelo.setText("V0005");
            break;
        case 5: txtPrecioViaje.setText("170.15");
                txtVuelo.setText("V0006");
            break;
        case 6: txtPrecioViaje.setText("130.25");
                txtVuelo.setText("V0007");
            break;
        case 7: txtPrecioViaje.setText("120.05");
                txtVuelo.setText("V0008");
            break;
        case 8: txtPrecioViaje.setText("100.18");
                txtVuelo.setText("V0009");
            break;
        case 9: txtPrecioViaje.setText("550.80");
                txtVuelo.setText("V0010");
            break;
        case 10:txtPrecioViaje.setText("200.54");
                txtVuelo.setText("V0011");
            break;
            
    }
    
    }//GEN-LAST:event_cboDestinoActionPerformed
    
    private void txtCostoPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoPasajeActionPerformed
    
    }//GEN-LAST:event_txtCostoPasajeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
int msg = JOptionPane.showConfirmDialog(this, "Deseas Modificar el Registro","Modificar",JOptionPane.YES_NO_OPTION);
        if(msg == JOptionPane.YES_OPTION){
           Factura factura = FacturaController.buscar(txtTicket.getText());
            if(factura != null){
                factura.setDestino(cboDestino.getSelectedItem().toString());
                factura.setSalida(dia.format(txtSalida.getDate()));
                factura.setHora(txtHora.getText());
                factura.setClase(cboClase.getSelectedItem().toString()); 
                factura.setEquipaje(cboEquipaje.getSelectedItem().toString());
                factura.setTipoPago(cboTipo.getSelectedItem().toString());
                factura.setNombrePais(cboDestino.getSelectedItem().toString()); 
                factura.setPuertaEmbarque(cboPuerta.getSelectedItem().toString());
                
                factura.setTarifa(Double.parseDouble(txtTarifa.getText()));
                factura.setPrecioViaje(Double.parseDouble(txtPrecioViaje.getText()));
                factura.setCostoPasaje(Double.parseDouble(txtCostoPasaje.getText()));
                listar();
                FacturaController.grabar();
                
                JOptionPane.showMessageDialog(this,"Registro Actualizado satisfactoriamente!!!");
                
            }else{
                JOptionPane.showMessageDialog(this,"Objeto no encontrado!!!");
            }
        }       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscaDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaDNIKeyReleased
    dtmCliente.setNumRows(0);
        for(int i=0;i<ClienteController.size();i++){
           if(ClienteController.get(i).getDni().contains(txtBuscaDNI.getText())){
            Object[] vector=new Object[6];
            vector[0] = ClienteController.get(i).getNombre();
            vector[1] = ClienteController.get(i).getApellidoPaterno();
            vector[2] = ClienteController.get(i).getApellidoMaterno();
            vector[3] = ClienteController.get(i).getEstado();
            vector[4] = ClienteController.get(i).getDni();
            vector[5] = ClienteController.get(i).getSexo();
            dtmCliente.addRow(vector);
            }
        }
        tbCliente2.setModel(dtmCliente);
    }//GEN-LAST:event_txtBuscaDNIKeyReleased

    private void txtBuscaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaDNIActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
dtmFactura.setNumRows(0);
for(int i=0;i<FacturaController.size();i++){
    if(ClienteController.get(i).getDni().contains(txtBuscar.getText())){
        Object[] vector = new Object[20];
        vector[0] = FacturaController.get(i).getNumeroVuelo();
        vector[1] = FacturaController.get(i).getNombre();
        vector[2] = FacturaController.get(i).getApellidoPaterno();
        vector[3] = FacturaController.get(i).getApellidoMaterno();
        vector[4] = FacturaController.get(i).getDni(); 
        vector[5] = FacturaController.get(i).getSexo(); 
        vector[6] = FacturaController.get(i).getPartida();
        vector[7] = FacturaController.get(i).getDestino();
        vector[8] = FacturaController.get(i).getSalida();
        vector[9] = FacturaController.get(i).getHora();
        vector[10]= FacturaController.get(i).getAsiento();
        vector[11] = FacturaController.get(i).getClase(); 
        vector[12] = FacturaController.get(i).getEquipaje(); 
        vector[13] = FacturaController.get(i).getPuertaEmbarque(); 
        vector[14] = FacturaController.get(i).getTipoPago(); 
        vector[15] = FacturaController.get(i).getTicket(); 
        vector[16] = FacturaController.get(i).getTarifa();
        vector[17] = FacturaController.get(i).getPrecioViaje();
        vector[18] = FacturaController.get(i).getCostoPasaje();
        vector[19] = FacturaController.get(i).getEstado();
        
        
        dtmFactura.addRow(vector);
    }
 }
tbFactura.setModel(dtmFactura);    
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tbFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFacturaMouseClicked
    txtVuelo.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(),0).toString());
    txtNombre.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 1).toString());
    txtApePaterno.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 2).toString());
    txtApeMaterno.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 3).toString());
    txtDni.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 4).toString());
    txtSexo.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 5).toString());
    txtPartida.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 6).toString());
    cboDestino.setSelectedItem(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 7).toString());
    txtSalida.setDateFormatString(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 8).toString());
    txtHora.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 9).toString());
    txtAsiento.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 10).toString());
    cboClase.setSelectedItem(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 11).toString());
    cboEquipaje.setSelectedItem(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 12).toString());
    cboPuerta.setSelectedItem(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 13).toString());
    cboTipo.setSelectedItem(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 14).toString());
    txtTicket.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 15).toString());
    txtTarifa.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 16).toString());
    txtPrecioViaje.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 17).toString());
    txtCostoPasaje.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 18).toString());    
    txtEstado.setText(dtmFactura.getValueAt(tbFactura.getSelectedRow(), 19).toString());  
    }//GEN-LAST:event_tbFacturaMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String path="";
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        if(x==JFileChooser.APPROVE_OPTION)
        {
            path=j.getSelectedFile().getPath();
        }
        Document doc=new Document();
        try {
            doc.setPageSize(PageSize.A2.rotate());
            PdfWriter.getInstance(doc, new FileOutputStream(path + "abc1.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(18);
                    tbl.addCell("VUELO");
                    tbl.addCell("NOMBRE");
                    tbl.addCell("A. PATERNO");
                    tbl.addCell("A. MATERNO");
                    tbl.addCell("DNI");
                    tbl.addCell("PARTIDA");
                    tbl.addCell("DESTINO");
                    tbl.addCell("FECHA");
                    
                    tbl.addCell("ASIENTO");
                    tbl.addCell("CLASE");
                    tbl.addCell("EQUIPAJE");
                    tbl.addCell("PUERTA");
                    tbl.addCell("TIPO PAGO");
                    tbl.addCell("TICKET");
                    tbl.addCell("TARIFA");
                    tbl.addCell("P. VIAJE");
                    tbl.addCell("COSTO");
                   

        for(int i=0;i<tbFactura.getRowCount();i++){
            String vuelo=tbFactura.getValueAt(i, 0).toString();
            String nombre=tbFactura.getValueAt(i, 1).toString();
            String paterno=tbFactura.getValueAt(i, 2).toString();
            String materno=tbFactura.getValueAt(i, 3).toString();
            String dni=tbFactura.getValueAt(i, 4).toString();
            String partida=tbFactura.getValueAt(i, 6).toString();
            String destino=tbFactura.getValueAt(i, 7).toString();
            String fecha=tbFactura.getValueAt(i, 8).toString();
            
            String asiento=tbFactura.getValueAt(i, 10).toString();
            String clase=tbFactura.getValueAt(i, 11).toString();
            String equipaje=tbFactura.getValueAt(i, 12).toString();
            String puerta=tbFactura.getValueAt(i, 13).toString();
            String tipo=tbFactura.getValueAt(i, 14).toString();
            String ticket=tbFactura.getValueAt(i, 15).toString();
            String tarifa=tbFactura.getValueAt(i, 16).toString();
            String precio=tbFactura.getValueAt(i, 17).toString();
            String costo=tbFactura.getValueAt(i, 18).toString();

            tbl.addCell(vuelo);
            tbl.addCell(nombre);
            tbl.addCell(paterno);
            tbl.addCell(materno);
            tbl.addCell(dni);
            tbl.addCell(partida);
            tbl.addCell(destino);
            tbl.addCell(fecha);
           
            tbl.addCell(asiento);
            tbl.addCell(clase);
            tbl.addCell(equipaje);
            tbl.addCell(puerta);
            tbl.addCell(tipo);
            tbl.addCell(ticket);
            tbl.addCell(tarifa);
            tbl.addCell(precio);
            tbl.addCell(costo);



        }
        

        doc.add(tbl);
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmFactura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(frmFactura.class.getName()).log(Level.SEVERE, null, ex);
        } 
        doc.close();
 
    }//GEN-LAST:event_btnImprimirActionPerformed
public double hallartotalpasaje(){
    double a,b,c;
    a=Double.parseDouble(txtTarifa.getText());
    b=Double.parseDouble(txtPrecioViaje.getText());
    c=(a+b)*1.18; 
    return c;
}
public void hora(){
        Calendar calendario=new GregorianCalendar();
        Date horaactual=new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    public void run(){
        Thread current=Thread.currentThread();
        while(current==hilo){
            hora();
            txtHora.setText(hora+":"+minutos+":"+segundos);
        }
    }
 public void limpiar(){
         txtVuelo.setText("");
         txtNombre.setText("");
         txtApePaterno.setText("");
         txtApeMaterno.setText("");
         txtDni.setText("");
         txtSexo.setText("");
         cboDestino.setSelectedIndex(0);
         cboEquipaje.setSelectedIndex(0);
         txtEstado.setText("");
         cboTipo.setSelectedIndex(0);
         cboPuerta.setSelectedIndex(0);
         txtAsiento.setText("");
         txtTicket.setText("");
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboClase;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JComboBox<String> cboEquipaje;
    private javax.swing.JComboBox<String> cboPuerta;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tbCliente2;
    private javax.swing.JTable tbFactura;
    private javax.swing.JTextField txtApeMaterno;
    private javax.swing.JTextField txtApePaterno;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtBuscaDNI;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCostoPasaje;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPartida;
    private javax.swing.JTextField txtPrecioViaje;
    private com.toedter.calendar.JDateChooser txtSalida;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVuelo;
    // End of variables declaration//GEN-END:variables
}
